### ISSUE TITLE
Which USB line do you measure on?

### ISSUE THREAD

**Issue by adishavit** [twstokes/arduino-plasma-ball#1]
Can you show a diagram or a close up of which USB lines you performed your measurements on?

**Comment by twstokes** [comment]
Hello, I don't have any great diagrams but will try to explain here. He's an [overhead picture](https://www.tannr.com/wp-content/uploads/2015/10/IMG_0245-e1444793640430-1024x768.jpg).

The USB is only being used for power in this project and could be replaced with any other 5v DC source. Out of the four pins used by USB, only two were used in this project - ground and +5v DC. The other two pins (for data) aren't used at all.

The Arduino is just scanning in the voltage (notice there's a resistor in there) and averaging the value. If there's a large change (hand is put on the plasma ball), it falls below a threshold and triggers an event.

Hope this helps!

**Comment by adishavit** [comment]
I get it now. Thanks!
